web:
  build: .
  command: python wsgi.py
  ports:
    - "5000:5000"
  volumes:
    - .:/code
  links:
    - redis
  environment:
    - IMPALA_HOST
    - IMPALA_PORT
    - SECURITY_TOKEN
redis:
  image: redis
